# Generated by Django 6.0.3 on 2026-04-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='score',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=3),
        ),
    ]
