# Generated by Django 6.0.3 on 2026-04-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_grade_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
