# Generated by Django 5.2.1 on 2025-11-16 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_course_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Faculity',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.faculity'),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.department'),
        ),
    ]
