# Generated by Django 5.2.1 on 2025-11-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_student_faculity_student_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Faculity',
        ),
    ]
