# Generated by Django 5.2.1 on 2025-11-23 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.room'),
        ),
    ]
