# Generated by Django 5.2.1 on 2025-11-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_course_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='assignment',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='grade',
            name='attendance',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='grade',
            name='final_exam',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='grade',
            name='mid_term',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='grade',
            name='quiz',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseName',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='course',
            name='lecturer',
            field=models.ManyToManyField(related_name='courses', to='backend.lecturer'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.IntegerField(default=2),
        ),
    ]
