# Generated by Django 5.2.1 on 2025-11-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_grade_assignment_grade_attendance_grade_final_exam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='assignment',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='grade',
            name='attendance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='grade',
            name='final_exam',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='grade',
            name='mid_term',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='grade',
            name='quiz',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
