# Generated by Django 5.2.1 on 2025-12-03 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_grade_assignment_alter_grade_attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='backend.enrollment'),
        ),
    ]
