# Generated by Django 5.2.1 on 2025-12-03 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_grade_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='enrollment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.enrollment'),
        ),
    ]
