# Generated by Django 5.2.1 on 2025-12-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_course_department_alter_grade_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
