# Generated by Django 6.0.3 on 2026-04-04 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='admin_code',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='lecture_code',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_code',
        ),
    ]
